keys:
  - &users:
    - &bruno 1D7C28419079D3FED5DFF21CBD6743DAE6ABDF36
  - &hosts:
    - &sun age1uac49mthsp8vy8aeus5p00p55eeqvc24tpty7uru2dav9vl54gqsltp2y3
    - &mars age14lqjdh9v8x52hh4308xes87g3c5hrzuqrtpe2eq6qm8qpcz5r4dqlh7wm3
    - &mercury age1wyeym84q5xcpv3a2fq09nw68fvuqv6s47a3uvamcellx836r7usqwyrhre
    - &wsl age1aa2wdywz3tw89jfu8xscyfryauq62pt85829ge8qptcey2u2tf0qrc574w
    - &pluto age1e558626r86ckk0uw38ap6xcntna3ekptr456v0hvmd5kzd706slquwdzqs
    - &jupiter age1vjg7cvggccrfeymmh70s6nqlfumfyw8sf577t44muqxy8wpkv4zq5xcwar
    - &venus age183mu9f6kweta6dq8wuwpjz7wug8jj20uy4224rjwc78z8xe5afuslttjpy
creation_rules:
  - path_regex: modules/users/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *sun
        - *mars
        - *mercury
        - *wsl
        - *pluto
        - *jupiter
        - *venus
  - path_regex: modules/hosts/sun/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *sun
  - path_regex: modules/hosts/sun/secrets/.*\.sops$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *sun
  - path_regex: modules/hosts/mars/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *mars
  - path_regex: modules/hosts/mercury/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *mercury
  - path_regex: modules/hosts/wsl/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *wsl
  - path_regex: modules/hosts/pluto/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *pluto
  - path_regex: modules/hosts/jupiter/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *jupiter
  - path_regex: modules/hosts/venus/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *venus
  - path_regex: modules/hosts/saturn/secrets.yaml$
    key_groups:
      - pgp:
        - *bruno
