keys:
  - &users:
    - &bruno 1D7C28419079D3FED5DFF21CBD6743DAE6ABDF36
  - &hosts:
    - &venus age1zu50xpy6clr58sjs2nyw2rqtq52j4fcuft0pv0wdcepumyanya2sqdxzc8
creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *venus
  - path_regex: hosts/venus/secrets.ya?ml$
    key_groups:
      - pgp:
        - *bruno
        age:
        - *venus
