name: Build all hosts

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.list.outputs.hosts }}
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22
      - name: Flake check
        run: nix flake check

      - id: list
        run: |
          echo "hosts=$(nix eval --json .#nixosConfigurations --apply builtins.attrNames)" >> "$GITHUB_OUTPUT"

  build:
    needs: check
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJson(needs.check.outputs.hosts) }}
    steps:
      - uses: actions/checkout@v7

      - uses: wimpysworld/nothing-but-nix@687c797a730352432950c707ab493fcc951818d7 # v10
        with:
          hatchet-protocol: 'holster'

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          extra-conf: |
            build-dir = /nix/build

      - name: Setup Attic cache
        uses: ryanccn/attic-action@dc99f5eb1d5c0495aa26f7b56337b30011fa153e # v0
        with:
          endpoint: https://attic.external.brusapa.com
          cache: nix-config
          token: ${{ secrets.ATTIC_TOKEN }}
          skip-push: ${{ github.event_name != 'push' }}

      - name: Build ${{ matrix.host }}
        run: |
          nix build --no-link ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"