name: Build and cache

on:
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      hosts: ${{ steps.list.outputs.hosts }}
    steps:
      - uses: actions/checkout@v7
      - id: list
        run: |
          echo "hosts=$(ls modules/hosts | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  build:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: ${{ fromJson(needs.discover.outputs.hosts) }}
    steps:
      - uses: actions/checkout@v7

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: https://attic.external.brusapa.com
          cache: nix-config
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build ${{ matrix.host }}
        run: |
          nix build ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" \
            --no-link --print-out-paths | tee result-path

      - name: Push to attic
        run: attic push nix-config "$(cat result-path)"